# Generated by Django 4.0.4 on 2022-06-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0002_alter_fish_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
